### ISSUE TITLE
Did you ever get this working?

### ISSUE THREAD

**Issue by jrhicks** [tartinesKiller/cordova-plugin-nquire300-barcode#1]
I reviewed your README file, but I couldn't tell if you ever got the project working.

**Comment by tartinesKiller** [comment]
Hello there!
To be fair, I've never used this "lib" more than for a test. So I never bothered to write even a minimum amount of doc.
However, it works, and can:

- enable or disable the barcode scanner
- enable or disable the continuous read on the scanner
- enable or disable the good read led
- enable or disable the (awful) good read beep

on the NQuire 300 ([this](https://www.newland-id.com/product/nquire-300/)).
Is that what you have in mind?

If it can be useful for you, I'll write down how to use it.

**Comment by tartinesKiller** [comment]
Just updated the README, hope you can get it working now

**Comment by jrhicks** [comment]
Thank you.  These devices are really cool.  Maybe I can flesh out similar libraries for all the functionality the device offers.  Your project is inspiring.   ... Now if I can just get the darn task bar on Android 4.4.2 removed ... oof.

**Comment by tartinesKiller** [comment]
Yeah, quite cheap compared to others, and fun to work with!
I guess you want your app to be fullscreen, kiosk mode? (Can't swipe down notification bar, no virtual buttons, etc.)
I don't know if Cordova permits to directly access Android "layer" from app, but in Nativescript I do the following:
```
            // eslint-disable-next-line no-undef
            const View = android.view.View;
            const window = app.android.startActivity.getWindow();
            const decorView = window.getDecorView();
            decorView.setSystemUiVisibility(
                View.SYSTEM_UI_FLAG_LAYOUT_STABLE |
                View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION |
                View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN |
                View.SYSTEM_UI_FLAG_HIDE_NAVIGATION | // hide nav bar
                View.SYSTEM_UI_FLAG_FULLSCREEN | // hide status bar
                View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY);
```
in order to hide bars and prevent user from interacting with OS's ui parts.
It certainly won't work in Cordova, but making Cordova's plugins is quite easy. 
You can give [this lib](https://github.com/hkalina/cordova-plugin-kiosk) a try too.
